"""create users and tokens tables

Revision ID: a4ad1210e311
Revises: fec97e6314c5
Create Date: 2025-12-30 11:23:23.659238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import UTC, datetime

# revision identifiers, used by Alembic.
revision: str = "a4ad1210e311"
down_revision: Union[str, Sequence[str], None] = "fec97e6314c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(as_uuid=True)),
        sa.Column("username", sa.String(length=255)),
        sa.Column("hashed_password", sa.String(length=255)),
        sa.Column("is_active", sa.Boolean(), server_default=sa.sql.expression.true()),
        sa.Column("role", sa.String(), server_default=sa.text("USER")),
        sa.Column("created_at", sa.DateTime(), default=datetime.now(UTC)),
        sa.Column("updated_at", sa.DateTime(), default=datetime.now(UTC), onupdate=datetime.now(UTC)),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
        sa.Index("ix_users_username", "username"),
    )
    # op.create_index("ix_users_username", "users", ["username"], unique=False)
    op.create_table(
        "tokens",
        sa.Column("id", sa.Uuid(as_uuid=True)),
        sa.Column("user_id", sa.Uuid(as_uuid=True)),
        sa.Column("expires_at", sa.DateTime()),
        sa.Column("is_active", sa.Boolean(), default=True),
        sa.Column("ip_address", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), default=datetime.now(UTC)),
        sa.Column("updated_at", sa.DateTime(), default=datetime.now(UTC), onupdate=datetime.now(UTC)),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.Index("ix_tokens_user_id", "user_id"),
        sa.Index("ix_tokens_ip_address", "ip_address"),
    )
    # op.create_index("ix_tokens_ip_address", "tokens", ["ip_address"], unique=False)
    # op.create_index("ix_tokens_user_id", "tokens", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index("ix_tokens_user_id", table_name="tokens")
    # op.drop_index("ix_tokens_ip_address", table_name="tokens")
    op.drop_table("tokens")
    # op.drop_index("ix_users_username", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
